### ISSUE TITLE
Jeedom 3

### ISSUE THREAD

**Issue by foudepc83** [redbug26/jeedom-domoticz#3]
Hello,

Domoticz user and I wish that jeedom communicates with domoticz,
I bought this plugin that no longer works.
Why sell a plugin that no longer works since the update.
A fix for this plugin would be great.

Thank you very much.

**Comment by redbug26** [comment]
Fix was sent yesterday to Jeedom.
You could also get the source code via github.

git clone git@github.com:redbug26/jeedom-domoticz.git /usr/share/nginx/www/jeedom/plugins/domoticz/

**Comment by foudepc83** [comment]
I just saw, Really sorry, but thank you very much for your responsiveness and congratulations!

**Comment by redbug26** [comment]
Pas de problème :) N’hesitez pas si il y a un problème avec la mise à jour.
